/*
 * Copyright 2005 HBA Specto Incorporated
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
/* Generated by Together */

package com.hbaspecto.pecas.sd;

public interface SpaceTypeInterface
{
    // Methods to get the various costs from the Transition_costs table.
    double getConstructionCost(int costScheduleID);

    double getAdditionCost(int costScheduleID);

    double getDemolitionCost(int costScheduleID);

    double getRenovationCost(int costScheduleID);

    // Methods to get the various fees from the Development_fees table.
    double getDevlopmentFeePerUnitSpaceInitial(int feeScheduleID);

    double getDevlopmentFeePerUnitLandInitial(int feeScheduleID);

    double getDevlopmentFeePerUnitSpaceOngoing(int feeScheduleID);

    double getDevlopmentFeePerUnitLandOngoing(int feeScheduleID);

    String getName();

    /**
     * Method getGridCode.
     * 
     * @return String
     */
    int getSpaceTypeID();

}
