package com.hbaspecto.pecas.land;

import java.util.List;
import simpleorm.dataset.SQuery;
import simpleorm.sessionjdbc.SSessionJdbc;
import com.hbaspecto.pecas.sd.orm.ParcelsTemp_gen;

/**
 * Business rules class for table parcels_view.<br>
 * Will not be regenerated by SimpleORMGenerator, add any business rules to this class
 **/

public class ParcelsTemp
        extends ParcelsTemp_gen
        implements java.io.Serializable, ParcelInterface
{
    public static List<ParcelsTemp> getParcelsForTaz(SSessionJdbc session, int tazNumber)
    {

        System.out.println("Getting parcels ..." + tazNumber);

        final SQuery<ParcelsTemp> query = new SQuery<ParcelsTemp>(ParcelsTemp_gen.meta).eq(Taz,
                tazNumber);

        final List<ParcelsTemp> parcelsInCurrentTAZ = session.query(query);

        return parcelsInCurrentTAZ;
    }

    public static List<ParcelsTemp> getParcelsWithRandomNumber(SSessionJdbc session,
            int RandomNumber)
    {

        System.out.println("Getting parcels with random number: " + RandomNumber);

        final SQuery<ParcelsTemp> query = new SQuery<ParcelsTemp>(ParcelsTemp_gen.meta).eq(Randnum,
                RandomNumber);

        final List<ParcelsTemp> parcelsWithCurrentNumber = session.query(query);

        return parcelsWithCurrentNumber;
    }

    public static List<ParcelsTemp> getAllParcels(SSessionJdbc session)
    {

        System.out.println("Getting all parcels ...");

        final SQuery<ParcelsTemp> query = new SQuery<ParcelsTemp>(ParcelsTemp_gen.meta);

        final List<ParcelsTemp> allParcels = session.query(query);

        return allParcels;
    }

}
