package com.hbaspecto.pecas.sd.orm;

/**
 * Business rules class for table luzs.<br>
 * Will not be regenerated by SimpleORMGenerator, add any business rules to this class
 **/

public class Luzs
        extends Luzs_gen
        implements java.io.Serializable
{
}
